/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, June 14, 2017 at 12:25:42 PM China Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/994C4217-88DD-4F55-A016-55BDD5998C49/Xitu.app/Xitu
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Xitu/AVObject.h>
#import <Xitu/AVSubclassing.h>

@class NSString;

@interface AVUser : AVObject <AVSubclassing>

@property (nonatomic,copy) NSString * facebookToken; 
@property (nonatomic,copy) NSString * twitterToken; 
@property (nonatomic,copy) NSString * sinaWeiboToken; 
@property (nonatomic,copy) NSString * qqWeiboToken; 
@property (assign,nonatomic) BOOL isNew; 
@property (assign,nonatomic) BOOL mobilePhoneVerified; 
@property (nonatomic,copy) NSString * sessionToken; 
@property (nonatomic,copy) NSString * username; 
@property (nonatomic,copy) NSString * password; 
@property (nonatomic,copy) NSString * email; 
@property (nonatomic,copy) NSString * mobilePhoneNumber; 
+(void)requestPasswordResetWithPhoneNumber:(id)arg1 block:(/*^block*/id)arg2 ;
+(void)resetPasswordWithSmsCode:(id)arg1 newPassword:(id)arg2 block:(/*^block*/id)arg3 ;
+(void)logOut;
+(void)verifyMobilePhone:(id)arg1 withBlock:(/*^block*/id)arg2 ;
+(void)loginWithAuthData:(id)arg1 platform:(id)arg2 block:(/*^block*/id)arg3 ;
+(void)signUpOrLoginWithMobilePhoneNumberInBackground:(id)arg1 smsCode:(id)arg2 block:(/*^block*/id)arg3 ;
+(void)logInWithMobilePhoneNumberInBackground:(id)arg1 password:(id)arg2 block:(/*^block*/id)arg3 ;
+(void)logInWithUsernameInBackground:(id)arg1 password:(id)arg2 block:(/*^block*/id)arg3 ;
+(void)requestPasswordResetForEmailInBackground:(id)arg1 block:(/*^block*/id)arg2 ;
+(id)userOrSubclassUser;
+(id)parseClassName;
+(void)changeCurrentUser:(id)arg1 save:(BOOL)arg2 ;
+(id)followerQuery:(id)arg1 ;
+(id)logInWithUsername:(id)arg1 password:(id)arg2 error:(id*)arg3 ;
+(BOOL)logInWithUsername:(id)arg1 password:(id)arg2 block:(/*^block*/id)arg3 waitUntilDone:(BOOL)arg4 error:(id*)arg5 ;
+(id)userParameter:(id)arg1 password:(id)arg2 ;
+(id)logInWithMobilePhoneNumber:(id)arg1 password:(id)arg2 error:(id*)arg3 ;
+(BOOL)logInWithMobilePhoneNumber:(id)arg1 password:(id)arg2 block:(/*^block*/id)arg3 waitUntilDone:(BOOL)arg4 error:(id*)arg5 ;
+(void)internalBecomeWithSessionTokenInBackground:(id)arg1 block:(/*^block*/id)arg2 ;
+(id)logInWithMobilePhoneNumber:(id)arg1 smsCode:(id)arg2 error:(id*)arg3 ;
+(BOOL)logInWithMobilePhoneNumber:(id)arg1 smsCode:(id)arg2 block:(/*^block*/id)arg3 waitUntilDone:(BOOL)arg4 error:(id*)arg5 ;
+(void)logInWithMobilePhoneNumberInBackground:(id)arg1 smsCode:(id)arg2 block:(/*^block*/id)arg3 ;
+(id)signUpOrLoginWithMobilePhoneNumber:(id)arg1 smsCode:(id)arg2 error:(id*)arg3 ;
+(BOOL)signUpOrLoginWithMobilePhoneNumber:(id)arg1 smsCode:(id)arg2 block:(/*^block*/id)arg3 waitUntilDone:(BOOL)arg4 error:(id*)arg5 ;
+(void)removeCookies;
+(BOOL)requestPasswordResetForEmail:(id)arg1 error:(id*)arg2 ;
+(void)internalRequestPasswordResetForEmailInBackground:(id)arg1 block:(/*^block*/id)arg2 ;
+(void)enableAutomaticUser;
+(BOOL)isAutomaticUserEnabled;
+(void)disableAutomaticUser;
+(void)requestEmailVerify:(id)arg1 withBlock:(/*^block*/id)arg2 ;
+(void)requestMobilePhoneVerify:(id)arg1 withBlock:(/*^block*/id)arg2 ;
+(id)logInWithUsername:(id)arg1 password:(id)arg2 ;
+(void)logInWithUsernameInBackground:(id)arg1 password:(id)arg2 ;
+(void)logInWithUsernameInBackground:(id)arg1 password:(id)arg2 target:(id)arg3 selector:(SEL)arg4 ;
+(id)logInWithMobilePhoneNumber:(id)arg1 password:(id)arg2 ;
+(void)logInWithMobilePhoneNumberInBackground:(id)arg1 password:(id)arg2 ;
+(void)logInWithMobilePhoneNumberInBackground:(id)arg1 password:(id)arg2 target:(id)arg3 selector:(SEL)arg4 ;
+(void)becomeWithSessionTokenInBackground:(id)arg1 block:(/*^block*/id)arg2 ;
+(id)becomeWithSessionToken:(id)arg1 error:(id*)arg2 ;
+(void)requestLoginSmsCode:(id)arg1 withBlock:(/*^block*/id)arg2 ;
+(id)logInWithMobilePhoneNumber:(id)arg1 smsCode:(id)arg2 ;
+(void)logInWithMobilePhoneNumberInBackground:(id)arg1 smsCode:(id)arg2 ;
+(void)logInWithMobilePhoneNumberInBackground:(id)arg1 smsCode:(id)arg2 target:(id)arg3 selector:(SEL)arg4 ;
+(id)signUpOrLoginWithMobilePhoneNumber:(id)arg1 smsCode:(id)arg2 ;
+(void)signUpOrLoginWithMobilePhoneNumberInBackground:(id)arg1 smsCode:(id)arg2 ;
+(void)signUpOrLoginWithMobilePhoneNumberInBackground:(id)arg1 smsCode:(id)arg2 target:(id)arg3 selector:(SEL)arg4 ;
+(BOOL)requestPasswordResetForEmail:(id)arg1 ;
+(void)requestPasswordResetForEmailInBackground:(id)arg1 ;
+(void)requestPasswordResetForEmailInBackground:(id)arg1 target:(id)arg2 selector:(SEL)arg3 ;
+(id)followeeQuery:(id)arg1 ;
+(id)authDataFromSNSResult:(id)arg1 ;
+(id)nameOfPlatform:(int)arg1 ;
+(id)platformNameFromAuthData:(id)arg1 ;
+(id)authDataFromSNSResult:(id)arg1 platform:(id)arg2 error:(id*)arg3 ;
+(void)loginWithAuthData:(id)arg1 block:(/*^block*/id)arg2 ;
+(id)user;
+(id)query;
+(void)load;
+(id)currentUser;
+(id)userTag;
+(id)endPoint;
-(void)setMobilePhoneNumber:(NSString *)arg1 ;
-(NSString *)mobilePhoneNumber;
-(void)setEmail:(NSString *)arg1 ;
-(NSString *)email;
-(void)setPassword:(NSString *)arg1 ;
-(NSString *)password;
-(void)setUsername:(NSString *)arg1 ;
-(NSString *)username;
-(void)setSessionToken:(NSString *)arg1 ;
-(NSString *)sessionToken;
-(void)setMobilePhoneVerified:(BOOL)arg1 ;
-(BOOL)mobilePhoneVerified;
-(void)setIsNew:(BOOL)arg1 ;
-(BOOL)isNew;
-(void)setQqWeiboToken:(NSString *)arg1 ;
-(NSString *)qqWeiboToken;
-(void)setSinaWeiboToken:(NSString *)arg1 ;
-(NSString *)sinaWeiboToken;
-(void)setTwitterToken:(NSString *)arg1 ;
-(NSString *)twitterToken;
-(void)setFacebookToken:(NSString *)arg1 ;
-(NSString *)facebookToken;
-(void)addAuthData:(id)arg1 platform:(id)arg2 block:(/*^block*/id)arg3 ;
-(void)signUpInBackgroundWithBlock:(/*^block*/id)arg1 ;
-(id)linkedServiceNames;
-(id)preSave;
-(BOOL)shouldIncludeUpdateRequests;
-(void)postSave;
-(void)removeLocalData;
-(void)postDelete;
-(id)internalClassName;
-(id)initialBodyData;
-(BOOL)isAuthDataExistInMemory;
-(id)userDictionaryForCache;
-(id)getRoles:(id*)arg1 ;
-(BOOL)signUp:(id*)arg1 ;
-(void)updatePassword:(id)arg1 newPassword:(id)arg2 block:(/*^block*/id)arg3 ;
-(void)isAuthenticatedWithSessionToken:(id)arg1 callback:(/*^block*/id)arg2 ;
-(id)getRolesAndThrowsWithError:(id*)arg1 ;
-(void)getRolesInBackgroundWithBlock:(/*^block*/id)arg1 ;
-(BOOL)signUp;
-(BOOL)signUpAndThrowsWithError:(id*)arg1 ;
-(void)signUpInBackground;
-(void)signUpInBackgroundWithTarget:(id)arg1 selector:(SEL)arg2 ;
-(void)updatePassword:(id)arg1 newPassword:(id)arg2 withTarget:(id)arg3 selector:(SEL)arg4 ;
-(void)setNewFlag:(BOOL)arg1 ;
-(void)follow:(id)arg1 userDictionary:(id)arg2 andCallback:(/*^block*/id)arg3 ;
-(id)followeeQuery;
-(id)followerQuery;
-(void)follow:(id)arg1 andCallback:(/*^block*/id)arg2 ;
-(void)unfollow:(id)arg1 andCallback:(/*^block*/id)arg2 ;
-(void)getFollowers:(/*^block*/id)arg1 ;
-(void)getFollowees:(/*^block*/id)arg1 ;
-(void)getFollowersAndFollowees:(/*^block*/id)arg1 ;
-(int)platformFromName:(id)arg1 ;
-(BOOL)isInternalSupportPlatform:(id)arg1 ;
-(void)deleteAuthDataForPlatform:(id)arg1 block:(/*^block*/id)arg2 ;
-(void)addAuthData:(id)arg1 block:(/*^block*/id)arg2 ;
-(id)userDictionary;
-(id)snapshot;
-(BOOL)isAuthenticated;
-(id)postData;
@end

