/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, June 14, 2017 at 12:25:41 PM China Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/994C4217-88DD-4F55-A016-55BDD5998C49/Xitu.app/Xitu
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface ThirdLoginModel : NSObject {

	int _type;
	NSString* _uid;
	NSString* _openid;
	NSString* _accessToken;
	NSString* _expirationIn;
	NSString* _username;

}

@property (nonatomic,retain) NSString * uid;                       //@synthesize uid=_uid - In the implementation block
@property (nonatomic,retain) NSString * openid;                    //@synthesize openid=_openid - In the implementation block
@property (nonatomic,retain) NSString * accessToken;               //@synthesize accessToken=_accessToken - In the implementation block
@property (nonatomic,retain) NSString * expirationIn;              //@synthesize expirationIn=_expirationIn - In the implementation block
@property (nonatomic,retain) NSString * username;                  //@synthesize username=_username - In the implementation block
@property (assign,nonatomic) int type;                             //@synthesize type=_type - In the implementation block
-(void)setExpirationIn:(NSString *)arg1 ;
-(NSString *)expirationIn;
-(void)setType:(int)arg1 ;
-(int)type;
-(NSString *)uid;
-(void)setUid:(NSString *)arg1 ;
-(void)setAccessToken:(NSString *)arg1 ;
-(void)setOpenid:(NSString *)arg1 ;
-(NSString *)openid;
-(void)setUsername:(NSString *)arg1 ;
-(NSString *)username;
-(NSString *)accessToken;
@end

